name: CI

on: [push]

jobs:
  sast_scan:
    name: Run SAST scan via bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install bandit
        run: |
          pip install bandit
      - name: Run bandit scan
        run: |
          bandit -r . -ll -ii -o bandit_report.json -f json
      
      - name: Upload bandit report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: bandit-findings
          path: bandit_report.json

  image_scan:
    name: Run image scan via docker scout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build application image
        run: docker build -t pygoat:ci${{ github.sha }}  .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        if: always()
        with:
          image-ref: pygoat:ci${{ github.sha }}
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          format: table
          exit-code: 1

      # - name: Upload Trivy report
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: trivy-findings
      #     path: trivy-report.json
