name: CI

on: [push]

jobs:
  sast_scan:
    name: Run SAST scan via bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install bandit
        run: |
          pip install bandit
      - name: Run bandit scan
        run: |
          bandit -r . -ll -ii -f sarif -o bandit-results.sarif

      - name: Upload Bandit SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: bandit-results.sarif

  image_scan:
    name: Run container image scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build application image
        run: docker build -t pygoat:ci${{ github.sha }}  .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        if: always()
        with:
          image-ref: pygoat:ci${{ github.sha }}
          vuln-type: os,library
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          format: table
          version: latest
          exit-code: 1

      - name: Generate Trivy SARIF for code scanning
        uses: aquasecurity/trivy-action@0.33.1
        if: always()
        with:
          image-ref: pygoat:ci${{ github.sha }}
          vuln-type: os,library
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          version: latest
          exit-code: 0

      - name: Upload Trivy SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: trivy-results
          path: trivy-results.sarif
